[package]
name = "ttrpc"
version = "0.1.0"
authors = ["Hui Zhu <teawater@antfin.com>"]
edition = "2018"
license = "Apache-2.0"
keywords = ["ttrpc", "protobuf", "rpc"]
readme = "README.md"
repository = "https://github.com/alipay/ttrpc-rust"
homepage = "https://github.com/alipay/ttrpc-rust"
description = "A Rust version of ttrpc."

[dependencies]
protobuf = { version = "2.0", optional = true }
bytes = { version = "0.4.11", optional = true }
log = "0.4"
nix = "0.14.1"
byteorder = "1.3.2"

[features]
default = ["protobuf-codec"]
protobuf-codec = ["protobuf"]

[[example]]
name = "client"
path = "examples/client.rs"

[dev-dependencies]
log = "0.4.6"
simple-logging = "2.0.2"
nix = "0.14.1"

