name: Sanity Check
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - labeled
      - unlabeled

jobs:
  commits_check_job:
    runs-on: ubuntu-latest
    name: Commits Check
    steps:
    - name: Get PR Commits
      id: 'get-pr-commits'
      uses: tim-actions/get-pr-commits@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Commit Body Check
      uses: tim-actions/commit-body-check@master
      with:
        commits: ${{ steps.get-pr-commits.outputs.commits }}
    - name: DCO Check
      uses: tim-actions/dco@master
      with:
        commits: ${{ steps.get-pr-commits.outputs.commits }}
  pr_wip_check:
    runs-on: ubuntu-latest
    name: WIP Check
    steps:
    - name: WIP Check
      uses: tim-actions/wip-check@master
      with:
        labels: '["do-not-merge", "wip", "rfc"]'
        keywords: '["WIP", "wip", "RFC", "rfc"]'
