[package]
name = "ttrpc-codegen"
version = "0.2.4"
edition = "2018"
authors = ["The AntFin Kata Team <kata@list.alibaba-inc.com>"]
license = "Apache-2.0"
keywords = ["codegen", "ttrpc", "protobuf"]
description = "Rust codegen for ttrpc using ttrpc-compiler crate"
categories = ["network-programming", "development-tools::build-utils"]
repository = "https://github.com/containerd/ttrpc-rust/tree/master/ttrpc-codegen"
homepage = "https://github.com/containerd/ttrpc-rust/tree/master/ttrpc-codegen"
readme = "README.md"


[dependencies]
protobuf = "2.28.0"
# protobuf-codegen3 is a protobuf-codegen version that supports proto3 optional fields better
protobuf-codegen = { package = "protobuf-codegen3", version = "2.28.2" }
# protobuf-codegen-pure3 is a protobuf-codegen-pure version that supports proto3 optional fields
protobuf-codegen-pure = { package = "protobuf-codegen-pure3", version = "2.28.2" }
ttrpc-compiler = "0.4.4"
